Repository cilium/workerpool, pull requests merged in 2023-02, with the labels that each got.

#42 update golangci-lint to v1.51.1, test with Go 1.20
  .github/workflows/tests.yml
  .golangci.yml
Labels: kind/enhancement, area/testing

#43 doc: document how to cancel the context of the task funcs
  workerpool.go
Labels: area/documentation, kind/enhancement

#44 add NewWithContext
  workerpool.go
  workerpool_test.go
Labels: kind/feature
